# Generated by Django 5.0.3 on 2024-03-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_is_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_logout',
            field=models.BooleanField(default=False),
        ),
    ]
